(function(){'use strict';DKRegister.value("passiveSkills",{
        dashCapacitor: { name: 'DASH CAPACITOR', icon: '↯', rarity: 'uncommon', price: 48, desc: 'Dashes leave a damaging lightning trail.', flag: 'dashCapacitor' },
        phoenixSigil: { name: 'PHOENIX SIGIL', icon: '♨', rarity: 'epic', price: 112, desc: 'Revive once at 40% HP and burn nearby enemies.', flag: 'phoenixSigil' },
        orbitingWard: { name: 'ORBITING WARD', icon: '◌', rarity: 'rare', price: 78, desc: 'A permanent ward circles you, blocking bullets and hurting foes.', flag: 'orbitingWard' },
        executioner: { name: 'EXECUTIONER', icon: '†', rarity: 'rare', price: 72, desc: '+40% damage to enemies below 25% HP.', flag: 'executioner' },
        manaShield: { name: 'MANA SHIELD', icon: '◇', rarity: 'rare', price: 80, desc: 'Spend 16 mana to absorb an otherwise damaging hit.', flag: 'manaShield' },
        alchemist: { name: 'ALCHEMIST', icon: '♧', rarity: 'uncommon', price: 52, desc: 'Burn, freeze, shock, and time effects deal 35% more damage.', flag: 'alchemist' },
        scavenger: { name: 'SCAVENGER', icon: '¤', rarity: 'common', price: 34, desc: 'Armory purchases heal 1 HP; elites drop two extra coins.', flag: 'scavenger' },
        calmMind: { name: 'CALM MIND', icon: '≈', rarity: 'common', price: 36, desc: '+20 max mana and +45% mana restored by pickups.', flag: 'calmMind' },
        gunslinger: { name: 'GUNSLINGER SCRIPT', icon: '⁙', rarity: 'uncommon', price: 55, desc: 'Every fifth Gun trigger adds two free angled rounds.', flag: 'gunslinger' },
        closeQuarters: { name: 'CLOSE QUARTERS', icon: '⚔', rarity: 'uncommon', price: 56, desc: 'Melee hits shorten armor recovery and restore a small amount of armor.', flag: 'closeQuarters' },
        spellEcho: { name: 'SPELL ECHO', icon: '◌', rarity: 'rare', price: 79, desc: 'Every sixth Magic cast repeats at 55% power without paying mana.', flag: 'spellEcho' },
        biomeScholar: { name: 'BIOME SCHOLAR', icon: '▤', rarity: 'rare', price: 82, desc: 'Living room objects grant two Resonance marks instead of one.', flag: 'biomeScholar' },
        blastHarness: { name:'BLAST HARNESS',icon:'◉',rarity:'uncommon',price:50,desc:'Bazookas and explosions gain +25% damage and radius.',flag:'blastHarness' },
        tacticalSling: { name:'TACTICAL SLING',icon:'⌁',rarity:'uncommon',price:52,desc:'AR bursts tighten; every eighth rifle round critically pierces.',flag:'tacticalSling' },
        coolingJacket: { name:'COOLING JACKET',icon:'≋',rarity:'uncommon',price:51,desc:'Sustained SMG fire ramps to +30% damage and restores mana on every twentieth hit.',flag:'coolingJacket' },
        shellBandolier: { name:'SHELL BANDOLIER',icon:'⁙',rarity:'uncommon',price:53,desc:'Shotguns fire +2 pellets and deal +20% point-blank damage.',flag:'shellBandolier' },
        eliteBreaker: { name:'ELITE BREAKER',icon:'◆',rarity:'rare',price:75,desc:'+25% elite damage. Elite kills restore 2 armor and 40 mana.',flag:'eliteBreaker' },
        glassRelay: { name:'GLASS RELAY',icon:'◇',rarity:'rare',price:74,desc:'Every projectile gains +1 pierce with only 6% less base damage.',flag:'glassRelay' },
        emergencyPlating: { name:'EMERGENCY PLATING',icon:'⬡',rarity:'rare',price:78,desc:'Negate the first damaging hit of every wave phase.',flag:'emergencyPlating' },
        manaCapacitor: { name:'MANA CAPACITOR',icon:'↯',rarity:'rare',price:76,desc:'Every 60 mana spent restores 1 armor and emits an arc pulse.',flag:'manaCapacitor' },
        bloodCompass: { name:'BLOOD COMPASS',icon:'✥',rarity:'rare',price:79,desc:'Critical executions restore 0.5 HP and point toward wounded prey.',flag:'bloodCompass' },
        momentumSpurs: { name:'MOMENTUM SPURS',icon:'»',rarity:'uncommon',price:54,desc:'Moving continuously builds up to +24% attack speed; stopping releases the stored burst.',flag:'momentumSpurs' },
        coinFoundry: { name:'COIN FOUNDRY',icon:'¤',rarity:'epic',price:101,desc:'Held coins grant up to +25% damage; spending coins keeps half the charge this wave.',flag:'coinFoundry' },
        elementalCrucible: { name:'ELEMENTAL CRUCIBLE',icon:'✣',rarity:'epic',price:108,desc:'Applying a second elemental status detonates a damaging reaction and spreads both.',flag:'elementalCrucible' }
    },"skills/passives");}());
