/* Dungeon Knight Japanese Localization v1.0.0
 * This file is also bundled as Dungeon Knight's built-in Japanese locale.
 */
var DungeonKnightJapaneseLocalization = {
  preload(DK) {
    const text = {
      'Play': 'プレイ',
      'PLAY': 'プレイ',
      'Multiplayer': 'マルチプレイヤー',
      'MULTIPLAYER': 'マルチプレイヤー',
      'Settings': '設定',
      'SETTINGS': '設定',
      'Statistics': '統計',
      'STATS': '統計',
      'Editor': 'エディター',
      'EDITOR MODE': 'エディターモード',
      'Mods': 'MOD',
      'Quit': '終了',
      'Back': '戻る',
      'BACK': '戻る',
      'Main Menu': 'メインメニュー',
      'MAIN': 'メイン',
      'SELECT AN OPTION': '項目を選択',
      'CHOOSE YOUR PATH': '進む道を選択',
      'CHOOSE SESSION TYPE': 'セッション形式を選択',
      'Single Player': 'シングルプレイヤー',
      'SINGLE PLAYER': 'シングルプレイヤー',
      'OFFLINE · 1 PLAYER': 'オフライン · 1人',
      'ONLINE · 1–4 PLAYERS · P2P': 'オンライン · 1～4人 · P2P',
      'LOCAL': 'ローカル',
      'HOST': 'ホスト',
      'GUEST': 'ゲスト',
      'RELAY READY': 'リレー準備完了',
      'ROOM SERVER': 'ルームサーバー',
      'REINFORCEMENTS': '増援',
      'LANGUAGE': '言語',
      'Language': '言語',
      'RESOLUTION': '解像度',
      'DISPLAY & INTERFACE': '表示とインターフェース',
      'UI SCALE': 'UIスケール',
      'HUD OPACITY': 'HUD透明度',
      'CAMERA DISTANCE': 'カメラ距離',
      'UI MOTION': 'UIアニメーション',
      'RESET UI SETTINGS': 'UI設定をリセット',
      '85% · COMPACT': '85% · コンパクト',
      '100% · DEFAULT': '100% · 標準',
      '115% · LARGE': '115% · 大',
      '130% · EXTRA LARGE': '130% · 特大',
      'SOFT': '弱',
      'BALANCED': 'バランス',
      'HIGH': '高',
      'FAR': '遠い',
      'DEFAULT': '標準',
      'CLOSE': '近い',
      'FULL': 'フル',
      'REDUCED': '軽減',
      '100% · NATIVE': '100% · ネイティブ',
      '85% · BALANCED': '85% · バランス',
      '70% · PERFORMANCE': '70% · パフォーマンス',
      'Changes are saved on this device.': '変更はこの端末に保存されます。',
      'Audio': 'オーディオ',
      'AUDIO': 'オーディオ',
      'Master volume': 'マスター音量',
      'Combat SFX': '戦闘効果音',
      'UI SFX': 'UI効果音',
      'World SFX': '環境効果音',
      'Music': '音楽',
      'Mute all': 'すべてミュート',
      'SFX volume': '効果音の音量',
      'Sound effects adapt to stereo position and distance. Settings persist on this device.': '効果音は定位と距離に応じて変化します。設定はこの端末に保存されます。',
      'HALL OF RECORDS': '記録の間',
      'CAREER TELEMETRY': 'プレイ統計',
      'WEAPONS': '武器',
      'BOSSES': 'ボス',
      'BEST WAVE': '最高ウェーブ',
      'HIGH SCORE': 'ハイスコア',
      'Weapons discovered': '発見した武器',
      'Bosses catalogued': '記録したボス',
      'Local save': 'ローカルセーブ',
      'CHOOSE CLASS': 'クラスを選択',
      'CLASS SELECT': 'クラス選択',
      'Select Class': 'クラス選択',
      'Classes': 'クラス',
      'Class details': 'クラス詳細',
      'CHOOSE YOUR KNIGHT': 'ナイトを選択',
      'Choose a class. Your starter is a random Common weapon matched to that style.': 'クラスを選択してください。プレイスタイルに合うCommon武器がランダムで支給されます。',
      'Each path begins with a random Common weapon suited to that class.': '各クラスは、その戦闘スタイルに合うCommon武器をランダムで所持して開始します。',
      'Each discipline begins with a random Common weapon calibrated to its combat profile.': '各戦闘分野は、その戦闘特性に調整されたCommon武器をランダムで所持して開始します。',
      'AVAILABLE': '使用可能',
      'COMBAT DISCIPLINE': '戦闘分野',
      'HEALTH': '体力',
      'TRAIT': '特性',
      'CREDITS': 'クレジット',
      'LOADOUT SETUP': 'ロードアウト設定',
      'SELECT DISCIPLINE': '戦闘分野を選択',
      'Melee': '近接',
      'Gunner / Archer': 'ガンナー / アーチャー',
      'Magic': '魔法',
      'Independent': '独立系',
      'The Bulwark': 'ブルワーク',
      'The Deadeye': 'デッドアイ',
      'The Arcanist': 'アーカニスト',
      'The Wanderer': 'ワンダラー',
      'THE BULWARK': 'ブルワーク',
      'THE DEADEYE': 'デッドアイ',
      'THE ARCANIST': 'アーカニスト',
      'THE WANDERER': 'ワンダラー',
      'Bastion Tempo': 'バスティオン・テンポ',
      'Deadeye Rhythm': 'デッドアイ・リズム',
      'Arcane Overflow': 'アーケイン・オーバーフロー',
      'Arsenal Savant': 'アーセナル・サヴァント',
      'Stronger melee attacks, guarded swings, and faster armor recovery after close kills.': '近接攻撃が強化され、攻撃中の防御性能が上がり、近距離キルでアーマー回復が早まります。',
      'Faster projectiles; every seventh shot becomes a tracer.': '投射物が高速化し、7発ごとにトレーサー弾になります。',
      'Stronger spells; mana spent charges free echoes.': '魔法が強化され、消費したマナで無料のエコー詠唱をチャージします。',
      'Stronger spells; restore 2 mana every 2 seconds and find mana drops more often.': '魔法が強化され、2秒ごとにマナを2回復し、敵からマナオーブを得られる確率が少し上がります。',
      '+18% magic and status damage. Restore 2 mana every 2 seconds; spending 40 mana releases a free 55% spell echo.': '魔法・状態異常ダメージ+18%。2秒ごとにマナを2回復し、マナを累計40消費すると威力55%のエコー詠唱を無料で放ちます。',
      'A 300-mana reserve, a slow personal mana pulse, and a slightly better chance to find mana from defeated enemies.': '最大マナ300。ゆっくりとマナを自力回復し、倒した敵からマナオーブを得られる確率が少し上がります。',
      'Switching disciplines grants adaptive power.': '武器系統を切り替えると適応強化を得ます。',
      'STARTING WEAPON': '初期武器',
      'RANDOM COMMON': 'ランダムCommon',
      'CONTINUE': '続ける',
      'ROOMS': 'ルーム',
      'MULTIPLAYER ROOMS': 'マルチプレイヤールーム',
      'CONNECTING': '接続中',
      'PLAYER NAME': 'プレイヤー名',
      'UPDATE RATE': '更新レート',
      'CREATE ROOM': 'ルーム作成',
      'REFRESH': '更新',
      'LOADING ROOMS…': 'ルームを読み込み中…',
      'Up to four players. Only the host can start the game.': '最大4人。ゲームを開始できるのはホストのみです。',
      'WAITING ROOM': '待機ルーム',
      'READY': '準備完了',
      'START': '開始',
      'WAITING FOR HOST': 'ホストを待機中',
      'ONLINE SESSION': 'オンラインセッション',
      'SESSION LOBBY': 'セッションロビー',
      'LIVE RUN': '進行中のラン',
      'PRIORITY TARGET': '優先目標',
      'MOVE · ATTACK · TEST WEAPON': '移動 · 攻撃 · 武器テスト',
      'INVENTORY': 'インベントリ',
      'WAVE': 'ウェーブ',
      'ENEMIES': '敵',
      'SCORE': 'スコア',
      'COINS': 'コイン',
      'ARMOR': 'アーマー',
      'MANA': 'マナ',
      'HP': 'HP',
      'PHASE': 'フェーズ',
      'TARGET': 'ターゲット',
      'AWAITING ATTACK': '攻撃待機中',
      'PAUSED': '一時停止',
      'SYSTEM PAUSE': 'システム一時停止',
      'SIMULATION HALTED. RESUME WHEN READY.': 'シミュレーション停止中。準備ができたら再開してください。',
      'THE DUNGEON WILL WAIT.': 'ダンジョンは待っています。',
      'RESUME': '再開',
      'STOP RUN': 'ランを終了',
      'PRESS AGAIN TO STOP': 'もう一度押して終了',
      'PRESS STOP AGAIN TO END THIS RUN': 'もう一度「ランを終了」を押して確定してください。',
      'YOU DIED': '死亡しました',
      'RUN ENDED': 'ラン終了',
      'RUN SUSPENDED': 'ラン中断',
      'SESSION ENDED': 'セッション終了',
      'THE DUNGEON KEEPS ITS COINS.': '失ったコインはダンジョンに残ります。',
      'BUILD ITEMS': 'ビルドアイテム',
      'RETRY': '再挑戦',
      'RUN INVENTORY': 'ラン・インベントリ',
      'Equip any owned weapon or active skill. The dungeon stays paused.': '所持している武器やアクティブスキルを装備できます。この画面ではゲームは一時停止します。',
      'Review the current loadout. Simulation remains paused while this dashboard is open.': '現在のロードアウトを確認します。この画面を開いている間はシミュレーションが停止します。',
      'ACTIVE SKILLS': 'アクティブスキル',
      'PASSIVES & PACTS': 'パッシブ & パクト',
      'DUNGEON MEMORIES': 'ダンジョンの記憶',
      'STATUS & BUFFS': '状態 & バフ',
      'RETURN': '戻る',
      'THE ARMORY': '武器庫',
      'ARMORY OPEN': '武器庫オープン',
      'APPROACH A RELIC TO INSPECT IT': 'レリックに近づいて調べる',
      'APPROACH AN ITEM': 'アイテムに近づく',
      'APPROACH AN ITEM TO INSPECT IT': 'アイテムに近づいて調べる',
      'PRIVATE STOCK · TEST BUILDS ON THE CENTER TARGET': '個人保管庫 · 中央ターゲットでビルドをテスト',
      'LOADOUT BAY': 'ロードアウトベイ',
      'CENTER TARGET READY': '中央ターゲット準備完了',
      'OWNED': '所持済み',
      'BUY': '購入',
      'REROLL': '再抽選',
      'DESCEND': '降りる',
      'SOLD': '売却済み',
      'NO COST': '無料',
      'MAXIMUM LEVEL': '最大レベル',
      'FORGEBOUND CRAFTING TABLE': 'フォージバウンド作業台',
      'Choose a recipe from the book, then match its weapon and material pattern.': 'レシピを選び、必要な武器と素材の組み合わせを揃えてください。',
      'RECIPE BOOK': 'レシピブック',
      'CRAFTING PATTERN': 'クラフト構成',
      'CRAFT': 'クラフト',
      'RETURN TO ARMORY': '武器庫へ戻る',
      'RECIPE': 'レシピ',
      'DESCRIPTION': '説明',
      'WEAPON': '武器',
      'CONTROLLED WEAPON TEST': '武器テストエリア',
      'RANGE MARKERS 180 / 360 / 540': '距離マーカー 180 / 360 / 540',
      'WEAPON FORGE': '武器鍛造台',
      'CRAFTING TABLE': '作業台',
      'INSPECT MODELS, PARTS & RECIPES': 'モデル、部品、レシピを確認',
      'OPEN TABLE': '作業台を開く',
      'ITEM FABRICATOR': 'アイテム製造機',
      'Select a blueprint, then supply the required weapon parts and materials.': '設計図を選び、必要な武器部品と素材を投入してください。',
      'BLUEPRINTS': '設計図',
      'REQUIRED PARTS': '必要部品',
      'BACK TO LOADOUT BAY': 'ロードアウトベイへ戻る',
      'COMMON': 'コモン',
      'UNCOMMON': 'アンコモン',
      'RARE': 'レア',
      'EPIC': 'エピック',
      'MYTHICAL': 'ミシカル',
      'LEGENDARY': 'レジェンダリー',
      'PHASE I': 'フェーズ I',
      'PHASE II · ENRAGED': 'フェーズ II · 激昂',
      'PHASE III · APEX': 'フェーズ III · 極致',

      'Content Manager': 'MODマネージャー',
      'Mods': 'MOD',
      'Shape your dungeon': 'ダンジョンを自分好みに',
      'Import trusted packages, choose what runs, then restart once to apply the new loadout.': '信頼できるパッケージを読み込み、有効にするMODを選び、一度再起動して新しい構成を適用します。',
      'Import Mod': 'MODをインポート',
      'Import ZIP': 'ZIPをインポート',
      'Create': '作成',
      'Search installed mods': 'インストール済みMODを検索',
      'Installed': 'インストール済み',
      'Modding Guide': 'MOD制作ガイド',
      'Reload to apply': '再読み込みして適用',
      'Restart now': '今すぐ再起動',
      'Create Mod': 'MODを作成',
      'Starter project': 'スタータープロジェクト',
      'Name': '名前',
      'Mod ID': 'MOD ID',
      'Author': '作者',
      'Description': '説明',
      'Cancel': 'キャンセル',
      'Create & Install': '作成してインストール',
      'Search': '検索',
      'No description.': '説明なし。',
      'No description provided.': '説明がありません。',
      'Export ZIP': 'ZIPを書き出す',
      'Earlier': '前へ',
      'Later': '後へ',
      'On': 'オン',
      'Off': 'オフ',
      'Source': 'ソース',
      'Game': 'ゲーム',
      'Multiplayer': 'マルチプレイヤー',
      'Dependencies': '依存関係',
      'None': 'なし',
      'ASHBOUND': '灰縛り',
      'RIMEBOUND': '霜縛り',
      'MIRAGE-BORN': '蜃気楼生まれ',
      'ARCBOUND': '雷縛り',
      'HOLLOWED': '虚ろの者',
      'SANGUINE': '血染め',
      'BRIARBOUND': '茨縛り',
      'DROWNED': '水没者',
      'GALE-KISSED': '風の祝福者',
      'RUNEBOUND': 'ルーン縛り',
      'FACETED': '多面晶',
      'PULSE-GROWN': '鼓動育ち',
      'FORGE-BORN': '炉生まれ',
      'CLOCKBOUND': '時計縛り',
      'LUNAR': '月影',
      'MYCELIAL': '菌糸体',

      'THE PALACE': '宮殿',
      'CRYO ARCHIVE': '氷結書庫',
      'DUNES OF TIME': '時の砂丘',
      'TESLA KEEP': 'テスラ砦',
      'GRAVITY WELL': '重力井戸',
      'BLOOD CATHEDRAL': '血の大聖堂',
      'BRIAR COURT': '茨の宮廷',
      'DROWNED BELFRY': '水没鐘楼',
      'TEMPEST AERIE': '嵐の高巣',
      'GILDED ARCHIVE': '黄金書庫',
      'PRISM VAULT': 'プリズム保管庫',
      'PULSE MARSH': '脈動湿地',
      'FURNACE RELIQUARY': '炉熱聖遺物庫',
      'PENDULUM WORKS': '振り子工房',
      'MOON OSSUARY': '月骨納堂',
      'SPORE GROTTO': '胞子洞窟',
      'DARK SPIRIT': 'ダーク・スピリット',
      "THE KNIGHT'S LAST SHADOW": '騎士の最後の影',
      'GLACIAL ARCHIVIST': '氷河の司書',
      'KEEPER OF WINTER': '冬の番人',
      'HOURGLASS COLOSSUS': '砂時計の巨像',
      'THE BURIED SECOND': '埋もれた一秒',
      'COIL SOVEREIGN': 'コイル・ソヴリン',
      'THE LIVING CIRCUIT': '生ける回路',
      'EVENT HORIZON': '事象の地平線',
      'MOUTH OF THE FOUNDRY': '鋳造所の口',
      'ROSE ABBESS': '薔薇の修道院長',
      'THE SCARLET VOW': '緋色の誓い',
      'BRIAR STAG': '茨角の雄鹿',
      'HEART OF THE ROOTS': '根の心臓',
      'DROWNED BELLKEEPER': '水没した鐘守',
      'TOLL OF THE DEEP': '深淵の鐘音',
      'TEMPEST ROC': 'テンペスト・ロック',
      'WING ABOVE THE KEEP': '砦を覆う翼',
      'THE GRAND INDEX': '大索引',
      'LAST WORD OF GOLD': '黄金の最後の言葉',
      'PRISM WYRM': 'プリズム・ワーム',
      'REFLECTION WITHOUT END': '終わりなき反射',
      'CIRCUIT TOAD': 'サーキット・トード',
      'HEARTBEAT OF THE MARSH': '湿地の鼓動',
      'FURNACE TYRANT': '炉熱の暴君',
      'KING OF THE RELIQUARY': '聖遺物庫の王',
      'PENDULUM ENGINE': 'ペンデュラム・エンジン',
      'MASTER OF THE SECOND': '一秒の支配者',
      'ECLIPSE HOUND': 'エクリプス・ハウンド',
      'HUNTER OF THE OSSUARY': '納骨堂の狩人',
      'MYCELIAL MONARCH': '菌糸の王',
      'THE COURT BENEATH': '地下の宮廷',

      'Gnawer': 'ノーワー',
      'Hex Slinger': 'ヘックス・スリンガー',
      'Iron Belly': 'アイアン・ベリー',
      'Spiral Mage': 'スパイラル・メイジ',
      'Nova Husk': 'ノヴァ・ハスク',
      'Grave Caller': 'グレイヴ・コーラー',
      'Orbit Wisp': 'オービット・ウィスプ',
      'Red Ram': 'レッド・ラム',
      'Bulwark': 'ブルワーク',
      'Cinder Lobber': 'シンダー・ロバー',
      'Blood Leech': 'ブラッド・リーチ',
      'Briar Burrower': 'ブライア・バロワー',
      'Undertow Cantor': 'アンダートウ・カンター',
      'Living Scribe': 'リビング・スクライブ',
      'Mirror Prism': 'ミラー・プリズム',
      'Glass Colony': 'グラス・コロニー',
      'Glass Shardling': 'グラス・シャードリング',
      'Cask Imp': 'カスク・インプ',
      'Ice Mason': 'アイス・メイソン',
      'Root Weaver': 'ルート・ウィーバー',
      'Mirror Duelist': 'ミラー・デュエリスト',
      'Slag Knight': 'スラグ・ナイト',
      'Second Thief': 'セカンド・シーフ',
      'Moonbone Archer': 'ムーンボーン・アーチャー',
      'Spore Host': 'スポア・ホスト',
      'Vault Skitter': 'ヴォルト・スキッター',
      'Powder Surveyor': 'パウダー・サーベイヤー',
      'Veil Stalker': 'ヴェイル・ストーカー',
      'War-Script Bearer': 'ウォースクリプト・ベアラー',
      'Mana Lantern Mite': 'マナ・ランタン・マイト',
      'Chain Warden': 'チェイン・ウォーデン',
      'Ash Mauler': 'アッシュ・モーラー',
      'Frost Lantern': 'フロスト・ランタン',
      'Dune Scarab': 'デューン・スカラベ',
      'Arc Tetherer': 'アーク・テザラー',
      'Rose Chorister': 'ローズ・コリスター',
      'Tide Skater': 'タイド・スケーター',
      'Mirror Mimic': 'ミラー・ミミック',
      'Spore Mortar': 'スポア・モーター',
      'Armory Target': '武器庫ターゲット'
    };

    Object.assign(text, {
      'Main menu': 'メインメニュー',
      'Saved on this device': 'この端末に保存済み',
      'Quit game': 'ゲームを終了',
      'General': '一般',
      'Video': '映像',
      'Interface': 'インターフェース',
      'Accessibility': 'アクセシビリティ',
      'Controls': '操作',
      'Mobile': 'モバイル',
      'Debug': 'デバッグ',
      'Primary input': '主な入力方法',
      'Mouse & keyboard': 'マウスとキーボード',
      'Autosave': '自動保存',
      'On': 'オン',
      'Off': 'オフ',
      'Pause when unfocused': '画面を離れたら一時停止',
      'Arrow keys, WASD, Enter, Tab, and Escape work throughout the menus.': 'メニューは矢印キー、WASD、Enter、Tab、Escでも操作できます。',
      'Resolution scale': '解像度スケール',
      'Display mode': '表示モード',
      'Windowed': 'ウィンドウ',
      'Fullscreen': 'フルスクリーン',
      'Frame-rate limit': 'フレームレート上限',
      'Unlimited': '無制限',
      'Effect quality': 'エフェクト品質',
      'Balanced': 'バランス',
      'Low': '低',
      'Vertical sync': '垂直同期',
      'Browser controlled': 'ブラウザーに従う',
      'UI scale': 'UIスケール',
      'HUD opacity': 'HUDの不透明度',
      'Camera distance': 'カメラ距離',
      'Damage numbers': 'ダメージ表示',
      'All hits': 'すべて表示',
      'Critical only': 'クリティカルのみ',
      'Player name labels': 'プレイヤー名表示',
      'Thai and Japanese use native font stacks and full IME composition support.': 'タイ語と日本語では、それぞれに適したフォントとIME入力を使用します。',
      'PC controls': 'PC操作',
      'Move up': '上へ移動',
      'Move down': '下へ移動',
      'Move left': '左へ移動',
      'Move right': '右へ移動',
      'Attack': '攻撃',
      'Dash': 'ダッシュ',
      'Use skill': 'スキル使用',
      'Switch weapon': '武器切り替え',
      'Inventory': 'インベントリ',
      'Pause': 'ポーズ',
      'Reset controls': '操作を初期化',
      'Choose an action, then press a keyboard key or mouse button. Duplicate bindings are swapped.': 'アクションを選び、割り当てたいキーまたはマウスボタンを押してください。重複した割り当ては入れ替わります。',
      'Press a key…': 'キーを入力…',
      'Mobile controls': 'モバイル操作',
      'Attack control': '攻撃操作',
      'Mobile attack control': 'モバイル攻撃操作',
      'Attack button': '攻撃ボタン',
      'Aim joystick': '照準ジョイスティック',
      'Automatic fire': '自動攻撃',
      'Control size': '操作ボタンの大きさ',
      'Control opacity': '操作ボタンの不透明度',
      'Customize layout': 'レイアウトを編集',
      'Reset layout': 'レイアウトを初期化',
      'The aim joystick fires while held and points independently from movement.': '照準ジョイスティックは押している間攻撃し、移動とは別方向を狙えます。',
      'Customize mobile controls': 'モバイル操作をカスタマイズ',
      'Drag the movement stick or action cluster. Keep both inside the safe area.': '移動スティックまたはアクション群をドラッグしてください。安全領域の内側に配置してください。',
      'Done': '完了',
      'Reset': 'リセット',
      'Debug overlay': 'デバッグ表示',
      'Performance': 'パフォーマンス',
      'Network': 'ネットワーク',
      'Full report': '詳細レポート',
      'Copy diagnostic report': '診断レポートをコピー',
      'Timing percentages measure active frame work. They help find expensive rendering, simulation, and network conditions.': '処理時間の割合から、描画・シミュレーション・通信の負荷が高い状況を確認できます。',
      'Menu motion': 'メニューアニメーション',
      'Reduced': '軽減',
      'Reduced motion keeps every control available while shortening movement.': '動きを軽減しても、すべての操作はそのまま利用できます。',
      'Reset settings': '設定を初期化',
      'Online': 'オンライン',
      'Connecting': '接続中',
      'Player name': 'プレイヤー名',
      'Update rate': '更新頻度',
      '30 Hz · Fixed': '30 Hz · 固定',
      'Every room uses the same optimized simulation cadence.': 'すべてのルームで最適化済みの同じ更新頻度を使用します。',
      'Create Room': 'ルーム作成',
      'Refresh': '更新',
      'Loading rooms…': 'ルームを読み込み中…',
      'Up to four players. Only the host can start the game.': '最大4人。ゲームを開始できるのはホストだけです。',
      'Waiting Room': '待機ルーム',
      'Ready': '準備完了',
      'Move · Attack · Test weapon': '移動 · 攻撃 · 武器テスト',
      'Start': '開始',
      'Hide UI': 'UIを隠す',
      'Show UI': 'UIを表示',
      'Class details': 'クラス詳細',
      'Health': '体力',
      'Armor': 'アーマー',
      'Mana': 'マナ',
      'Trait': '特性',
      'Starting weapon': '開始武器',
      'Random Common': 'ランダムなCommon武器',
      'Continue': '続ける',
      'Paused': '一時停止',
      'Resume': '再開',
      'During this run': 'このプレイ中',
      'Customize mobile layout': 'モバイル配置を編集',
      'Current run': '現在のプレイ',
      'Progress': '進行状況',
      'Remaining': '残り',
      'Class': 'クラス',
      'Review and equip items. The game remains paused while this screen is open.': '所持品の確認と装備を行います。この画面を開いている間、ゲームは一時停止します。',
      'Weapons': '武器',
      'Active Skills': 'アクティブスキル',
      'Passives & Pacts': 'パッシブと契約',
      'Dungeon Memories': 'ダンジョンの記憶',
      'Status & Buffs': '状態と強化',
      'Return': '戻る',
      'Run ended': '探索終了',
      'You Died': '力尽きた',
      'Party Defeated': 'パーティー敗北',
      'The dungeon keeps its coins.': 'コインはダンジョンに残されます。',
      'Wave': 'ウェーブ',
      'Score': 'スコア',
      'Build items': 'ビルド項目',
      'Collecting frame data…': 'フレーム情報を計測中…',
      'Diagnostic report copied.': '診断レポートをコピーしました。',
      'Could not copy automatically.': '自動でコピーできませんでした。'
    });

    const descriptions = {
      activeSkills: {
        aegisPulse: 'Eで周囲の敵弾を消去し、短時間バリアを得ます。',
        frostNova: 'Eで周囲を凍結し、ダメージを与え、敵弾を氷に閉じ込めます。',
        thunderTotem: 'Eで6秒間トーテムを設置し、近くの敵同士へ雷を連鎖させます。',
        riftStep: 'Eで照準方向へ長距離ワープし、通過した敵を斬り、一瞬無敵になります。',
        bladeHalo: 'Eで7本の赤い剣を6秒間召喚。周囲を旋回し、敵弾を防ぎつつ敵を斬ります。',
        phaseClock: 'Eで4秒間、すべての敵と敵弾を遅くします。',
        crimsonSurge: 'EでHPを2消費し、5秒間ダメージと攻撃速度を大幅に強化します。',
        overclock: 'Eで7秒間攻撃速度を大幅に上げ、マナオーブの回復量を75%増加させます。',
        echoSeal: 'Eを押すと8秒間、すべての攻撃が遅れてエコー攻撃を発生させます。',
        singularity: 'Eで照準地点に操作可能な特異点を作り、敵を吸い寄せて引き裂きます。'
      },
      passiveSkills: {
        dashCapacitor: 'ダッシュすると、ダメージを与える電撃の軌跡を残します。',
        phoenixSigil: '死亡時に一度だけHP40%で復活し、周囲の敵を炎上させます。',
        orbitingWard: '恒久的なシールドが周囲を旋回し、敵弾を防ぎながら敵にダメージを与えます。',
        executioner: 'HP25%未満の敵へのダメージが40%増加します。',
        manaShield: 'ダメージを受ける直前にマナ16を消費し、その攻撃を防ぎます。',
        alchemist: '炎上、凍結、感電、時間系の状態異常ダメージが35%増加します。',
        scavenger: '武器庫で購入するたびHPを1回復し、Elite敵がコインを2枚多く落とします。',
        calmMind: '最大マナ+20。マナオーブの回復量が45%増加します。',
        gunslinger: '銃の5回目のトリガーごとに、斜め方向へ追加弾を2発無料で発射します。',
        closeQuarters: '近接攻撃でアーマー回復待ち時間が短縮され、少量のアーマーを回復します。',
        spellEcho: '6回目の魔法詠唱ごとに、マナを消費せず55%威力で再詠唱します。',
        biomeScholar: '部屋のインタラクティブオブジェクトから得るResonanceが1ではなく2になります。',
        blastHarness: 'バズーカと爆発のダメージ・範囲が25%増加します。',
        tacticalSling: 'ARバーストの精度が上がり、8発ごとのライフル弾がクリティカルかつ貫通になります。',
        coolingJacket: 'SMGの連続命中でダメージが最大30%上昇し、20ヒットごとにマナを回復します。',
        shellBandolier: 'ショットガンのペレット+2。至近距離ダメージが20%増加します。',
        eliteBreaker: 'Eliteへのダメージ+25%。Elite撃破時にアーマー2とマナ40を回復します。',
        glassRelay: '全弾の貫通+1。ただし基礎ダメージが6%低下します。',
        emergencyPlating: '各ウェーブ区間で最初に受けるダメージを無効化します。',
        manaCapacitor: 'マナを累計60消費するたびアーマー1を回復し、電撃波を放ちます。',
        bloodCompass: 'クリティカルキルでHP0.5を回復し、傷ついた敵の方向を示します。',
        momentumSpurs: '移動し続けると攻撃速度が最大24%上昇。停止時に蓄積した力を放出します。',
        coinFoundry: '所持コインに応じてダメージが最大25%上昇。コイン消費後もウェーブ終了まで半分の効果を維持します。',
        elementalCrucible: '2種類目の属性状態を付与すると反応爆発が起こり、両方の状態を周囲へ拡散します。'
      },
      pacts: {
        bloodLedger: '獲得コイン+35%。ただし敵の最大HP+18%。',
        glassOath: 'ダメージ+32%。ただし最大HP-3。',
        eliteHunt: '運+20。Elite敵の出現数が2倍になります。',
        hasteCovenant: '移動速度・攻撃速度+14%。ただし敵弾も高速化します。'
      },
      stats: {
        vitality: '最大HP+3、HPを3回復。',
        muscle: '全ダメージ+15%。',
        reflex: '攻撃速度+14%。',
        boots: '移動速度+10%。',
        focus: 'クリティカル率+10%。',
        armor: '耐久+1.5。各ポイントで受けるダメージを軽減します。',
        luck: '運+18。武器庫で高レアリティ品が出る確率が上がります。',
        magnet: '回収範囲+110。',
        manaWell: '最大マナ+35、マナを35回復。',
        channeling: 'マナオーブの回復量+35%。',
        vampirism: '直接ダメージの2.5%を吸血します。',
        evasion: '回避率+9%。'
      }
    };

    function format(value) {
      let m;
      if ((m = /^BEST WAVE (\d+) · HIGH SCORE (\d+)$/.exec(value))) return `最高ウェーブ ${m[1]} · ハイスコア ${m[2]}`;
      if ((m = /^WAVE (\d+)$/.exec(value))) return `ウェーブ ${m[1]}`;
      if ((m = /^WAVE (\d+) · PHASE (\d+)$/.exec(value))) return `ウェーブ ${m[1]} · フェーズ ${m[2]}`;
      if ((m = /^WAVE (\d+) · PHASE (\d+)\/(\d+)$/.exec(value))) return `ウェーブ ${m[1]} · フェーズ ${m[2]}/${m[3]}`;
      if ((m = /^ENEMIES (\d+)$/.exec(value))) return `敵 ${m[1]}`;
      if ((m = /^ENEMIES (\d+) · PHASE (\d+)\/(\d+)$/.exec(value))) return `敵 ${m[1]} · フェーズ ${m[2]}/${m[3]}`;
      if ((m = /^SCORE (\d+)$/.exec(value))) return `スコア ${m[1]}`;
      if ((m = /^COINS (\d+)$/.exec(value))) return `コイン ${m[1]}`;
      if ((m = /^ARMOR (.+)$/.exec(value))) return `アーマー ${m[1]}`;
      if ((m = /^MANA (.+)$/.exec(value))) return `マナ ${m[1]}`;
      if ((m = /^\+(.+) MANA$/.exec(value))) return `マナ +${m[1]}`;
      if ((m = /^HP (.+)$/.exec(value))) return `HP ${m[1]}`;
      if ((m = /^PHASE (.+)$/.exec(value))) return `フェーズ ${m[1]}`;
      if ((m = /^UPGRADE (.+) TO LV (\d+)$/.exec(value))) return `${m[1]} を LV ${m[2]} に強化`;
      if ((m = /^(\d+) COINS · FIRE \/ E$/.exec(value))) return `${m[1]} コイン · 射撃 / E`;
      if ((m = /^NEED (\d+) COINS$/.exec(value))) return `${m[1]} コイン必要`;
      if ((m = /^BUY (\d+)$/.exec(value))) return `購入 ${m[1]}`;
      if ((m = /^UPGRADE (\d+)$/.exec(value))) return `強化 ${m[1]}`;
      if ((m = /^ARMORY AT WAVE (\d+)$/.exec(value))) return `ウェーブ ${m[1]} で武器庫`;
      if ((m = /^DESCEND TO WAVE (\d+)$/.exec(value))) return `ウェーブ ${m[1]} へ降りる`;
      if ((m = /^ROOM (.+) · (20|30) HZ · HOST$/.exec(value))) return `ルーム ${m[1]} · ${m[2]} HZ · ホスト`;
      if ((m = /^ROOM (.+) · (20|30) HZ · WAITING FOR HOST$/.exec(value))) return `ルーム ${m[1]} · ${m[2]} HZ · ホスト待機中`;
      if ((m = /^Best wave (\d+) · High score (\d+)$/.exec(value))) return `最高ウェーブ ${m[1]} · ハイスコア ${m[2]}`;
      if ((m = /^Wave (\d+)$/.exec(value))) return `ウェーブ ${m[1]}`;
      if ((m = /^Enemies (\d+)$/.exec(value))) return `敵 ${m[1]}`;
      if ((m = /^Coins (\d+)$/.exec(value))) return `コイン ${m[1]}`;
      if ((m = /^CASTING · (.+)$/.exec(value))) return `詠唱中 · ${m[1]}`;
      if ((m = /^CHARGING · (.+)$/.exec(value))) return `チャージ中 · ${m[1]}`;
      if ((m = /^NEXT · (.+)$/.exec(value))) return `次 · ${m[1]}`;
      if ((m = /^RESOLUTION (\d+)%$/.exec(value))) return `解像度 ${m[1]}%`;
      if ((m = /^CAMERA ZOOM (\d+)%$/.exec(value))) return `カメラズーム ${m[1]}%`;
      if ((m = /^REROLL (\d+)$/.exec(value))) return `再抽選 ${m[1]}`;
      if ((m = /^WAITING (\d+)\/(\d+)$/.exec(value))) return `待機中 ${m[1]}/${m[2]}`;
      if ((m = /^(\d+)P · OPEN SLOT$/.exec(value))) return `${m[1]}P · 空き`;
      if ((m = /^(.+) FORGED TO LV (\d+)$/.exec(value))) return `${m[1]} · LV ${m[2]} に鍛造`;
      if ((m = /^(.+) · CALIBRATED TO LV (\d+)$/.exec(value))) return `${m[1]} · LV ${m[2]} に調整`;
      if ((m = /^FOCUS · (.+)$/.exec(value))) return `選択中 · ${m[1]}`;
      if ((m = /^MISSING · (.+)$/.exec(value))) return `不足 · ${m[1]}`;
      if ((m = /^(.+) · CRAFTED$/.exec(value))) return `${m[1]} · クラフト完了`;
      if ((m = /^(.+) ACQUIRED$/.exec(value))) return `${m[1]} · 入手`;
      if ((m = /^(.+) STORED IN INVENTORY$/.exec(value))) return `${m[1]} · インベントリに保管`;
      if ((m = /^(.+) (EQUIPPED|LEARNED|SWORN)$/.exec(value))) return `${m[1]} · ${m[2] === 'EQUIPPED' ? '装備' : m[2] === 'LEARNED' ? '習得' : '誓約'}`;
      if ((m = /^(.+) REMEMBERED · ARMORY OPEN$/.exec(value))) return `${m[1]} を記憶 · 武器庫オープン`;
      if ((m = /^LV (\d+) · (\d+)S COOLDOWN · (.+)$/.exec(value))) return `LV ${m[1]} · クールダウン ${m[2]}秒 · ${m[3]}`;
      if ((m = /^LV (\d+) · READY · (.+)$/.exec(value))) return `LV ${m[1]} · 使用可能 · ${m[2]}`;
      return value;
    }

    function describeWeapon(weapon) {
      if (!weapon) return '';
      const source = String(weapon._bundleOriginalDesc || weapon.desc || '').toLowerCase();
      const category = {
        MELEE: '近接武器',
        GUN: '銃器',
        MAGIC: '魔法武器',
        ARCHER: '射撃武器'
      }[weapon.category] || '武器';
      const parts = [`${category}。基礎ダメージ ${weapon.damage || 0}`];
      if (/seek|homing|hunt|curve/.test(source)) parts.push('標的を追尾');
      if (/pierc|through one|through two|through wall|ignore stone/.test(source)) parts.push('標的を貫通');
      if (/bounce|ricochet/.test(source)) parts.push('壁で跳弾');
      if (/burn|fire|ember|flame/.test(source)) parts.push('炎上を付与');
      if (/frost|freeze|chill|cold/.test(source)) parts.push('冷気または凍結を付与');
      if (/shock|lightning|thunder|electric/.test(source)) parts.push('電撃を付与');
      if (/explod|blast|burst|bomblet|rocket|shell/.test(source)) parts.push('爆発を発生');
      if (/return|home to the caster|backward|reverse/.test(source)) parts.push('軌道を戻る');
      if (/pull|drag|gravity|yank/.test(source)) parts.push('敵を引き寄せる');
      if (/reflect|erase hostile|blocking shots|destroys hostile|clears bullets|bullet-eating/.test(source)) parts.push('敵弾に干渉');
      if (/heal|restore/.test(source)) parts.push('条件達成でリソースを回復');
      if (/after|delayed|repeat|echo/.test(source)) parts.push('遅延または反復攻撃');
      if (/hold|full draw|perfect draw|perfect release/.test(source)) parts.push('チャージで攻撃挙動が変化');
      if (parts.length === 1) parts.push('固有の攻撃メカニクスを持つ');
      return parts.join('。') + '。';
    }

    DK.i18n.register('ja', {
      locale: 'ja',
      label: '日本語',
      fontFamily: '"Noto Sans JP", "Yu Gothic UI", "Yu Gothic", Meiryo, sans-serif',
      text,
      descriptions,
      format,
      describeWeapon
    });
    DK.log('Japanese localization registered.');
  }
};

if (typeof module !== 'undefined' && module && module.exports) {
  module.exports = DungeonKnightJapaneseLocalization;
} else if (typeof window !== 'undefined') {
  window.DK_BUNDLES = window.DK_BUNDLES || {};
  DungeonKnightJapaneseLocalization.preload({
    i18n: { register(locale, bundle) { window.DK_BUNDLES[locale] = bundle; } },
    log() {}
  });
}
