(function () {
  'use strict';

  DKRegister.value('biomes', [{
    name: 'THE PALACE',
    floor: '#151215',
    grid: '#2b2427',
    edge: '#57464b',
    accent: '#a53643',
    hazard: 'ember',
    prop: 'royalBrazier',
    resonance: 'ASHFIRE',
    enemy: 'bomber',
    enemy2: 'cinderling',
    mechanic: 'A dim royal hall lit by narrow window shafts. The carpet and statue remain readable while the corners stay in shadow.'
  }, {
    name: 'WINTER VAULT',
    floor: '#081119',
    grid: '#152733',
    edge: '#527b8e',
    accent: '#b8e7f2',
    hazard: 'frost',
    prop: 'iceCrate',
    resonance: 'WHITEOUT',
    enemy: 'charger',
    enemy2: 'frostshaper',
    mechanic: 'Break ice crates to create slow fields.'
  }, {
    name: 'SANDGLASS SEPULCHER',
    floor: '#171511',
    grid: '#2b2820',
    edge: '#5c5341',
    accent: '#aa9165',
    hazard: 'sand',
    prop: 'sandUrn',
    resonance: 'DUNEWAKE',
    enemy: 'boneArcher',
    enemy2: 'chronomancer',
    mechanic: 'Crack sand urns to create tailwind circles.'
  }, {
    name: 'ARC VAULT',
    floor: '#110f1a',
    grid: '#2b2441',
    edge: '#795ba2',
    accent: '#b477ff',
    hazard: 'storm',
    prop: 'arcCapacitor',
    resonance: 'OVERCHARGE',
    enemy: 'orbiter',
    enemy2: 'spiral',
    mechanic: 'Charge capacitors to discharge local chain arcs.'
  }, {
    name: 'VOID FOUNDRY',
    floor: '#100b13',
    grid: '#2e1934',
    edge: '#7d3d76',
    accent: '#ff4da6',
    hazard: 'void',
    prop: 'gravityCore',
    resonance: 'NULL TIDE',
    enemy: 'leech',
    enemy2: 'splitter',
    mechanic: 'Rupture gravity cores to create temporary singularities.'
  }, {
    name: 'CRIMSON CHAPEL',
    floor: '#180c10',
    grid: '#3d1d27',
    edge: '#8d4057',
    accent: '#ff6b8a',
    hazard: 'blood',
    prop: 'bloodRose',
    resonance: 'SCARLET VOW',
    enemy: 'leech',
    enemy2: 'summoner',
    mechanic: 'Cut blood roses to siphon nearby foes.'
  }, {
    name: 'VERDANT ROOTS',
    floor: '#101511',
    grid: '#202a21',
    edge: '#4e5e4d',
    accent: '#78936f',
    hazard: 'thorn',
    prop: 'heartPod',
    resonance: 'WILDBLOOM',
    enemy: 'briar',
    enemy2: 'rootweaver',
    mechanic: 'Burst heart-pods to snare nearby foes and recover life.'
  }, {
    name: 'SUNKEN CLOISTER',
    floor: '#09161b',
    grid: '#123743',
    edge: '#3c8292',
    accent: '#3bd5e6',
    hazard: 'tide',
    prop: 'tideBell',
    resonance: 'UNDERTOW',
    enemy: 'tidecaller',
    enemy2: 'nova',
    mechanic: 'Ring tide bells to reverse nearby hostile shots.'
  }, {
    name: 'CLOUD BASTION',
    floor: '#111923',
    grid: '#263c52',
    edge: '#7196b5',
    accent: '#bdeaff',
    hazard: 'cloud',
    prop: 'stormKite',
    resonance: 'SKY CHOIR',
    enemy: 'orbiter',
    enemy2: 'boneArcher',
    mechanic: 'Loose storm kites to create crossing wind-lances.'
  }, {
    name: 'GILDED ARCHIVE',
    floor: '#181208',
    grid: '#3c2e12',
    edge: '#8d7128',
    accent: '#ffd45a',
    hazard: 'glyph',
    prop: 'runeLectern',
    resonance: 'GOLD SCRIPT',
    enemy: 'scribe',
    enemy2: 'summoner',
    mechanic: 'Break rune lecterns for mana, coins, and exposed prey.'
  }, {
    name: 'GLASS OBSERVATORY',
    floor: '#0e151c',
    grid: '#203846',
    edge: '#6994ab',
    accent: '#a8efff',
    hazard: 'mirror',
    prop: 'mirrorObelisk',
    resonance: 'PRISMATIC',
    enemy: 'prism',
    enemy2: 'glassDuelist',
    mechanic: 'Shatter obelisks to release crystal hunters.'
  }, {
    name: 'NEON MARSH',
    floor: '#071716',
    grid: '#123a37',
    edge: '#317d74',
    accent: '#48ffd0',
    hazard: 'neon',
    prop: 'pulseReed',
    resonance: 'PULSEWAKE',
    enemy: 'sporeHost',
    enemy2: 'tidecaller',
    mechanic: 'Strike pulse reeds to chain luminous ripples.'
  }, {
    name: 'MOLTEN RELIQUARY',
    floor: '#180b08',
    grid: '#412019',
    edge: '#9b4632',
    accent: '#ff6a32',
    hazard: 'magma',
    prop: 'forgeAnvil',
    resonance: 'OVERFORGE',
    enemy: 'slagKnight',
    enemy2: 'bomber',
    mechanic: 'Strike anvils to release molten blades.'
  }, {
    name: 'CLOCKWORK CATACOMB',
    floor: '#15130d',
    grid: '#383321',
    edge: '#8f7b3d',
    accent: '#ffd36a',
    hazard: 'gear',
    prop: 'hourglassEngine',
    resonance: 'SECOND HAND',
    enemy: 'chronomancer',
    enemy2: 'orbiter',
    mechanic: 'Break hourglasses to reverse hostile shots and steal time.'
  }, {
    name: 'MOON OSSUARY',
    floor: '#0d1020',
    grid: '#24294d',
    edge: '#6670ad',
    accent: '#c9d1ff',
    hazard: 'moon',
    prop: 'lunarIdol',
    resonance: 'MOONFALL',
    enemy: 'boneArcher',
    enemy2: 'glassDuelist',
    mechanic: 'Crack lunar idols to release hunting crescent blades.'
  }, {
    name: 'SPORE GROTTO',
    floor: '#10150c',
    grid: '#29371e',
    edge: '#657d42',
    accent: '#b6e86b',
    hazard: 'spore',
    prop: 'sporeLantern',
    resonance: 'MYCELIUM',
    enemy: 'sporeHost',
    enemy2: 'leech',
    mechanic: 'Pop spore lanterns to spread poison blooms across nearby foes.'
  }], 'world/biomes');
  DKRegister.value('biomeArt', {
    ember: {
      tileA: '#1d191b',
      tileB: '#242023',
      seam: '#0d0b0c',
      wall: '#1e191c',
      wallTop: '#493a40',
      trim: '#84696d',
      land: '#0d0b0c',
      terrain: '#8d2734',
      structure: 'shadow royal palace',
      motif: 'royal',
      landscape: 'royalPalace',
      grade: 'rgba(64,16,22,.055)'
    },
    frost: {
      tileA: '#1b2b36',
      tileB: '#213440',
      seam: '#0e1c25',
      wall: '#172731',
      wallTop: '#3f6070',
      trim: '#a5ced9',
      land: '#0b202a',
      terrain: '#6da6b8',
      structure: 'snowbound sanctum',
      motif: 'ice',
      landscape: 'frozenSanctum',
      grade: 'rgba(104,190,220,.07)'
    },
    sand: {
      tileA: '#49443a',
      tileB: '#514b40',
      seam: '#2f2b25',
      wall: '#38332c',
      wallTop: '#776c58',
      trim: '#aa966f',
      land: '#211e19',
      terrain: '#827057',
      structure: 'buried court',
      motif: 'dune',
      landscape: 'duneCourt',
      grade: 'rgba(173,124,54,.045)'
    },
    storm: {
      tileA: '#57477a',
      tileB: '#63528b',
      seam: '#392e54',
      wall: '#4b3c67',
      wallTop: '#9d82c8',
      trim: '#e0c2ff',
      land: '#29223a',
      terrain: '#b879ff',
      structure: 'arc pillars',
      motif: 'circuit',
      landscape: 'arcPlate',
      grade: 'rgba(105,74,160,.055)'
    },
    void: {
      tileA: '#39203f',
      tileB: '#46264c',
      seam: '#241129',
      wall: '#311936',
      wallTop: '#7c3c7e',
      trim: '#ff74bd',
      land: '#120914',
      terrain: '#b33181',
      structure: 'void masonry',
      motif: 'rift',
      landscape: 'riftBasin',
      grade: 'rgba(52,8,64,.08)'
    },
    blood: {
      tileA: '#8a3b50',
      tileB: '#984359',
      seam: '#582334',
      wall: '#6b2c3e',
      wallTop: '#c9637d',
      trim: '#ffc0cd',
      land: '#4a1726',
      terrain: '#f3a0b5',
      structure: 'crimson arches',
      motif: 'rose',
      landscape: 'chapelAisle',
      grade: 'rgba(105,12,35,.055)'
    },
    thorn: {
      tileA: '#343c33',
      tileB: '#3a4338',
      seam: '#222921',
      wall: '#293129',
      wallTop: '#62705f',
      trim: '#81977b',
      land: '#171d17',
      terrain: '#62795d',
      structure: 'living root garden',
      motif: 'leaf',
      landscape: 'rootGarden',
      grade: 'rgba(32,73,40,.045)'
    },
    tide: {
      tileA: '#3e8190',
      tileB: '#4b909e',
      seam: '#285d69',
      wall: '#356c76',
      wallTop: '#86bac1',
      trim: '#cffcff',
      land: '#1f5966',
      terrain: '#82dce2',
      structure: 'flooded columns',
      motif: 'wave',
      landscape: 'waterIsles',
      grade: 'rgba(25,113,132,.055)'
    },
    cloud: {
      tileA: '#8eb5c9',
      tileB: '#9cc3d5',
      seam: '#63879a',
      wall: '#7195a7',
      wallTop: '#d8edf5',
      trim: '#ffffff',
      land: '#b9d5e2',
      terrain: '#eefaff',
      structure: 'sky ramparts',
      motif: 'wind',
      landscape: 'cloudCourt',
      grade: 'rgba(167,211,230,.035)'
    },
    glyph: {
      tileA: '#927746',
      tileB: '#a48a53',
      seam: '#614e2e',
      wall: '#74603b',
      wallTop: '#c6a967',
      trim: '#ffe6a0',
      land: '#49381e',
      terrain: '#bd3d45',
      structure: 'archive stacks',
      motif: 'rune',
      landscape: 'archiveCarpet',
      grade: 'rgba(137,94,28,.045)'
    },
    mirror: {
      tileA: '#76aaba',
      tileB: '#85bac8',
      seam: '#4b7887',
      wall: '#5c8795',
      wallTop: '#b5dae2',
      trim: '#f0fdff',
      land: '#437282',
      terrain: '#bdf6ff',
      structure: 'glass buttresses',
      motif: 'facet',
      landscape: 'prismCourt',
      grade: 'rgba(89,169,198,.045)'
    },
    neon: {
      tileA: '#397b6f',
      tileB: '#468b7e',
      seam: '#25584f',
      wall: '#32695f',
      wallTop: '#73b6a8',
      trim: '#a8ffe9',
      land: '#1c4a43',
      terrain: '#4affce',
      structure: 'luminous marshstone',
      motif: 'pulse',
      landscape: 'marshPools',
      grade: 'rgba(28,104,82,.055)'
    },
    magma: {
      tileA: '#8f432e',
      tileB: '#a14b33',
      seam: '#5c291f',
      wall: '#713225',
      wallTop: '#ce6744',
      trim: '#ffbd75',
      land: '#401912',
      terrain: '#ff7138',
      structure: 'forge blocks',
      motif: 'lava',
      landscape: 'magmaMoat',
      grade: 'rgba(134,45,16,.06)'
    },
    gear: {
      tileA: '#887547',
      tileB: '#9a8550',
      seam: '#5b4e2d',
      wall: '#6e603d',
      wallTop: '#bda768',
      trim: '#ffe5a0',
      land: '#3e361f',
      terrain: '#d9b84f',
      structure: 'clockwork walls',
      motif: 'gear',
      landscape: 'gearWorks',
      grade: 'rgba(111,86,28,.045)'
    },
    moon: {
      tileA: '#69729e',
      tileB: '#7780ac',
      seam: '#454d78',
      wall: '#555d85',
      wallTop: '#aab1d4',
      trim: '#f4f5ff',
      land: '#343a66',
      terrain: '#d7dcff',
      structure: 'ossuary pillars',
      motif: 'bone',
      landscape: 'boneMoon',
      grade: 'rgba(73,84,142,.06)'
    },
    spore: {
      tileA: '#647a47',
      tileB: '#71894f',
      seam: '#44552f',
      wall: '#53643c',
      wallTop: '#91a76a',
      trim: '#e3ffad',
      land: '#354429',
      terrain: '#c4f276',
      structure: 'fungal stone',
      motif: 'spore',
      landscape: 'fungalMoss',
      grade: 'rgba(70,99,35,.055)'
    }
  }, 'world/biomes');
})();
